DROP DATABASE IF EXISTS ComuniCode;
CREATE DATABASE ComuniCode;
USE ComuniCode;

DROP TABLE IF EXISTS CodiciPostali;

CREATE TABLE CodiciPostali (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Comune VARCHAR(255) NOT NULL,
    CAP VARCHAR(10) NOT NULL
);
